### ISSUE TITLE
how .json file was created

### ISSUE THREAD

**Issue by MohammedHAlali** [neheller/isic18#1]
Hello Nicholas Heller,

Thanks for uploading this awesome work. I've a question about step 5 of data preparation.
How .json file was created and what does it contain?
Because this part was not mentioned.

Thanks,
Mohammed

**Comment by neheller** [comment]
Hi Mohammed,

Sorry for the lack of clarity. The .json files came from the ISIC archive. When you select "Download Images and Metadata", every image file `<filename>.jpeg` comes with a corresponding `<filename>.json` which contains clinical information about the image. I used these to assign each image to a class. 

Please let me know if this is still unclear.

Regards,
Nick

**Comment by neheller** [comment]
Sorry - closed the issue by mistake.

**Comment by MohammedHAlali** [comment]
Hi Nick,

Now it is clear.
I was able to download the images and .json files from ISIC Archive Gallery:
https://www.isic-archive.com/#!/topWithHeader/onlyHeaderTop/gallery

Thanks,
Mohammed
